### ISSUE TITLE
Reg. ov5645_mipi Camera not working on IMX7 pico pi.  

### ISSUE THREAD

**Issue by amsurana** [technexion-android/platform_packages_apps_Camera2#1]
Hi,

I downloaded the Disk Image for Pico Pi here - ftp://download.technexion.net/demo_software/PICO/IMX7/pico-imx7-emmc/DiskImage/pico-imx7_pico-pi_android-8.0.0_QCA9377_lcd_800x480_20181115.zip

The camera seems to be detected, but the Camera App shows - No device found.

Serial Console Output, when device boots: 

```
random: fast init done
mxc_mipi-csi 30750000.mipi-csi: Registered sensor subdevice: ov5645_mipisubdev 3-003c
camera ov5645_mipi is found
usbcore: registered new interface driver uvcvideo
USB Video Class driver (1.1.1)
imx2-wdt 30280000.wdog: timeout 60 sec (nowayout=0)
```

ADB Logcat Output when Camera app is opened: 

```

--------- beginning of system
01-01 00:08:45.319   394   446 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.camera/.Camera bnds=[137,231][203,297] (has extras)} from uid 10013
--------- beginning of main
01-01 00:08:45.320   259  1118 I audio_hw_primary: start_output_stream_primary... -1287593088, device 2
01-01 00:08:45.324   259  1118 W audio_hw_primary: card 0, port 0 device 0x2
01-01 00:08:45.324   259  1118 W audio_hw_primary: rate 44100, channel 2 period_size 0xc0
01-01 00:08:45.351   394   440 I ThreadedRenderer: OpenGL ES 2.0 is disabled
01-01 00:08:45.378   263   263 I display : alloc cache buffer err:0
01-01 00:08:45.390  1124  1344 V CameraHolder: open camera 0
01-01 00:08:45.391   276  1180 I CameraService: CameraService::connect call (PID -1 "com.android.camera", camera ID 0) for HAL version default and Camera API version 1
01-01 00:08:45.404   284   692 D NuPlayerDriver: NuPlayerDriver(0xa67bf2a0) created, clientPid(276)
01-01 00:08:45.409   239   239 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
01-01 00:08:45.469   284  1345 D NuPlayerDriver: notifyListener_l(0xa67bf2a0), (1, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.470   284   284 D NuPlayerDriver: NuPlayerDriver(0xa80a7690) created, clientPid(276)
01-01 00:08:45.474   239   239 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
01-01 00:08:45.506   284  1347 D NuPlayerDriver: notifyListener_l(0xa80a7690), (1, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.508   284   376 D NuPlayerDriver: NuPlayerDriver(0xa80a73f0) created, clientPid(276)
01-01 00:08:45.509   239   239 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
01-01 00:08:45.525   284  1349 D NuPlayerDriver: notifyListener_l(0xa80a73f0), (1, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.525   276  1180 I Camera2ClientBase: Camera 0: Opened. Client: com.android.camera (PID 1124, UID 10048)
01-01 00:08:45.529   261   261 I FslCameraHAL: openDev:0: Opening camera device
01-01 00:08:45.529   261   261 I FslCameraHAL: openDev
01-01 00:08:45.529   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_PREVIEW(1)
01-01 00:08:45.530   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_STILL_CAPTURE(2)
01-01 00:08:45.530   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_VIDEO_RECORD(3)
01-01 00:08:45.530   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_VIDEO_SNAPSHOT(4)
01-01 00:08:45.530   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_ZERO_SHUTTER_LAG(5)
01-01 00:08:45.531   261   261 I FslCameraHAL: setTemplate:0: Setting already constructed template type CAMERA3_TEMPLATE_MANUAL(6)
01-01 00:08:45.533   276  1180 E Camera2-Parameters: generated preview size list is empty!!
01-01 00:08:45.533   276  1180 E Camera2Client: initializeImpl: Camera 0: unable to build defaults: Invalid argument (-22)
01-01 00:08:45.533   276  1180 E CameraService: connectHelper: Could not initialize client from HAL.
01-01 00:08:45.533   276  1180 I Camera2Client: Camera 0: Closed
01-01 00:08:45.533   276  1180 I Camera3-Device: disconnect: E
01-01 00:08:45.535   261   359 I FslCameraHAL: closeDev:0: Closing camera device
01-01 00:08:45.535   261   359 I FslCameraHAL: closeDev
01-01 00:08:45.535   261   322 I FslCameraHAL: state:0x201 can't go into stop state
01-01 00:08:45.535   276  1180 I Camera3-Device: disconnect: X
01-01 00:08:45.537   276   360 I Camera3-Device: disconnect: E
01-01 00:08:45.539   276  1180 I CameraService: disconnect: Disconnected client for camera 0 for PID 1124
01-01 00:08:45.540   276  1180 I Camera2ClientBase: Closed Camera 0. Client was: com.android.camera (PID 1124, UID 10048)
01-01 00:08:45.541   284   376 D NuPlayerDriver: reset(0xa67bf2a0) at state 4
01-01 00:08:45.541   284   376 D NuPlayerDriver: notifyListener_l(0xa67bf2a0), (8, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.541   284  1345 D NuPlayerDriver: notifyResetComplete(0xa67bf2a0)
01-01 00:08:45.546   284   692 D NuPlayerDriver: reset(0xa80a7690) at state 4
01-01 00:08:45.546   284   692 D NuPlayerDriver: notifyListener_l(0xa80a7690), (8, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.547   284  1347 D NuPlayerDriver: notifyResetComplete(0xa80a7690)
01-01 00:08:45.549   284   692 D NuPlayerDriver: reset(0xa80a73f0) at state 4
01-01 00:08:45.549   284   692 D NuPlayerDriver: notifyListener_l(0xa80a73f0), (8, 0, 0, -1), loop setting(0, 0)
01-01 00:08:45.549   284  1349 D NuPlayerDriver: notifyResetComplete(0xa80a73f0)
01-01 00:08:45.551  1124  1344 W CameraBase: An error occurred while connecting to camera 0: Status(-8): '10: connectHelper:1399: Failed to initialize camera "0": No such device (-19)'
01-01 00:08:45.552  1124  1344 E CameraHolder: fail to connect Camera
01-01 00:08:45.552  1124  1344 E CameraHolder: java.lang.RuntimeException: Fail to connect to camera service
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at android.hardware.Camera.<init>(Camera.java:510)
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at android.hardware.Camera.open(Camera.java:359)
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at com.android.camera.CameraHolder.open(CameraHolder.java:131)
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at com.android.camera.Util.openCamera(Util.java:267)
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at com.android.camera.Camera$3.run(Camera.java:1123)
01-01 00:08:45.552  1124  1344 E CameraHolder: 	at java.lang.Thread.run(Thread.java:764)
01-01 00:08:45.600  1124  1124 I ThreadedRenderer: OpenGL ES 2.0 is disabled
01-01 00:08:45.612  1124  1124 I ThreadedRenderer: OpenGL ES 2.0 is disabled
01-01 00:08:45.728   272   272 D SurfaceFlinger: duplicate layer name: changing com.android.camera/com.android.camera.Camera to com.android.camera/com.android.camera.Camera#1
01-01 00:08:45.781   275   386 W AudioFlinger: write blocked for 374 msecs, 3 delayed writes, thread 0xa809ba00
01-01 00:08:45.841  1124  1124 V camera  : surfaceChanged. w=592. h=444
01-01 00:08:45.852   263   365 I display : alloc cache buffer err:0
01-01 00:08:45.873   263  1315 I display : alloc cache buffer err:0
01-01 00:08:45.900   394   416 I ActivityManager: Displayed com.android.camera/.Camera: +555ms
01-01 00:08:45.906   394   440 I ThreadedRenderer: OpenGL ES 2.0 is disabled

```

Can you please support here?

**Comment by wigcheng** [comment]
Unfortunately, PICO-IMX7 does not support mipi camera function on Android at this moment, it's due to the NXP official cannot overcome the android framework layer without openGL support, thanks.

**Comment by axxios-Mark** [comment]
Will PICO-IMX6S support this camera?

**Comment by wigcheng** [comment]
PICO-IMX6S does support OV5645 mipi camera, thanks.
